const commandLineArgs = require('command-line-args');


// Here are the options. The jnode is going to be started using jamrun (a Python program).
// These options are going to be used by that program while starting the jnode.
// The jnode itself is embedded in the output generated by the jamc compiler.

// jnode --fog(-f)  --cloud(-c) --conf(-o)=filename.conf --debug(-d) --log(-l)=log.txt 
//       --registry(-r) --app(-a)=name


module.exports = function parseArgs() {

    const optdefs = [
        { name: 'fog', alias: 'f', type: Boolean},
        { name: 'cloud', alias: 'c', type: Boolean},
        { name: 'registry', alias: 'r', type: Boolean},
        { name: 'conf', alias: 'o', type: String},
        { name: 'app', alias: 'a', type: String},
        { name: 'log', alias: 'l', type: String},
    ];

    // Catch exceptions..
    try {
        var options = commandLineArgs(optdefs)
    } catch(e) {
        console.log(e.name);
        // there was an error.. what is it?
        process.exit(1);
    }

    return options;
}