module.exports = {
    id: {"name": 0},
    string: {"value": 0},
    number: {"value": 0},
    Async_activity: {"jcond": 1, "jtask_attr": 2, "decl": 3, "namespace": 4, "body": 5},
    Sync_activity: {"jcond": 2, "jtask_attr": 3, "return_type": 1, "decl": 4, "namespace": 5, "body": 6},
    Function_def: {"return_type": 0, "decl": 1, "body": 2},
    Prototype: {"return_type": 0, "pointer_list": 1, "name": 2, "params": 4, "gcc_attributes": 6},
    Declarator: {"pointer_list": 0, "name": 1, "gcc_asm": 2, "gcc_attribute": 3},
    Dir_declarator_PCall: {type: "Function_decl", "name": 0, "params": 1},
    Dir_declarator_PMember: {type: "Array_decl", "name": 0, "array": 1},
    Decl_specs: {"attributes_left": 0, "decl_type": 1, "attributes_right": 2},
    Pointer: {"qualifiers": 1},
    Pmember_decl: {type: "Array", "size": 0},
};
