module.exports = {
    id: {"name": 0},
    string: {"value": 0},
    number: {"value": 0},
    Expr: {"exprs": 0},
    Assign_expr_assign: {"lhs": 0, "op": 1, "rhs": 2},
    Cond_expr_cond: {"cond": 0, "then": 2, "else": 4},
    Lor_expr_lor: {type: "Binop_expr", "lhs": 0, "op": 1, "rhs": 2},
    Lar_expr_lar: {type: "Binop_expr", "lhs": 0, "op": 1, "rhs": 2},
    Ior_expr_ior: {type: "Binop_expr", "lhs": 0, "op": 1, "rhs": 2},
    Xor_expr_xor: {type: "Binop_expr", "lhs": 0, "op": 1, "rhs": 2},
    And_expr_and: {type: "Binop_expr", "lhs": 0, "op": 1, "rhs": 2},
    Eq_expr_eq: {type: "Binop_expr", "lhs": 0, "op": 1, "rhs": 2},
    Rel_expr_rel: {type: "Binop_expr", "lhs": 0, "op": 1, "rhs": 2},
    Shift_expr_shift: {type: "Binop_expr", "lhs": 0, "op": 1, "rhs": 2},
    Add_expr_add: {type: "Binop_expr", "lhs": 0, "op": 1, "rhs": 2},
    Mult_expr_mult: {type: "Binop_expr", "lhs": 0, "op": 1, "rhs": 2},
    Prefix_expr_Unary: {type: "Prefix_expr", "op": 0, "expr": 2},
    Unary_expr_Prefix: {type: "Prefix_expr", "op": 0, "expr": 1},
    Cast_expr_Cast: {type: "Cast_expr", "cast_type": 1, "expr": 3},
    Postfix_expr_Postfix: {type: "Postfix_expr", "expr": 0, "op": 2},
    Left_expr_Call: {type: "Funcall_expr", "name": 0, "args": 1},
    Left_expr_Array: {type: "Array_access_expr", "array": 0, "index": 2},
    Left_expr_Struct: {type: "Struct_access_expr", "struct": 0, "field": 2},
    Left_expr_Pointer: {type: "Pointer_access_expr", "pointer": 0, "field": 2},
    Primary_expr_GroupExpr: {type: "Paren_expr", "expr": 1},
    Async_activity: {"jcond": 1, "jtask_attr": 2, "name": 3, "params": 5, "namespace": 7, "body": 8},
    Sync_activity: {"return_type": 1, "pointer_list": 2, "jcond": 3, "jtask_attr": 4, "name": 5, "params": 7, "namespace": 9, "body": 10},
    Function_def: {"return_type": 0, "decl": 1, "body": 2},
    Prototype: {"return_type": 0, "pointer_list": 1, "name": 2, "params": 4, "gcc_attributes": 6},
    Declarator: {"pointer_list": 0, "name": 1, "gcc_asm": 2, "gcc_attribute": 3},
    Dir_declarator_PCall: {type: "Function_decl", "name": 0, "params": 1},
    Dir_declarator_PMember: {type: "Array_decl", "name": 0, "array": 1},
    Decl: {"decl_type": 0, "decls": 1},
    Decl_specs: {"attributes_left": 0, "decl_type": 1, "attributes_right": 2},
    Pointer: {"qualifiers": 1},
    Pmember_decl: {type: "Array", "size": 0},
    Param_decl_Declarator: {"param_type": 0, "name": 1},
    Param_decl_AbsDeclarator: {"param_type": 0, "name": 1},
    Label_stmt: {"label": 0, "stmt": 2},
    Case_stmt: {"cond": 1, "stmt": 3},
    Default_stmt: {"stmt": 2},
    Compound_stmt: {"block": 1, "sc": 3},
    If_stmt: {"cond": 2, "stmt": 4, "else": 6},
    Switch_stmt: {"cond": 2, "stmt": 4},
    While_stmt: {"cond": 2, "stmt": 4},
    DoWhile_stmt: {"cond": 4, "stmt": 1},
    For_stmt: {"expr_init": 2, "cond": 3, "expr_iter": 4, "stmt": 6},
    Goto_stmt: {"label": 1},
    Return_stmt: {"expr": 1},
};
