#!/bin/bash

die() {
    printf '%s\n' "$1" >&2
    exit 1
}

show_usage() {
    cat << EOF

Runs JAMScript instances in docker containers.
The docker version of the normal 'jam' commands

djam help   - prints this help
djam clean  - clean the setup left behind by old runs
djam close  - close terminals
djam kill   - kill a node
djam list   - lists all the JAMScript programs running in the system
djam pull   - pull the given docker image
djam run    - start a device, fog, or cloud
djam term   - show the tmux terminals of the running nodes


Type 'djam cmd --help' for more help on the specific command.

EOF
}

if [ -z $1 ] || [ $1 == "help" ]; then
    show_usage
    exit 0
fi

jcmd=$1
shift 1
params=$@


case $jcmd in
    list)
        jamlist $params
        ;;
    term)
        djamterm $params
        ;;
    kill)
        jamkill $params
        ;;
    clean)
        djamclean $params
        ;;
    run)
        djamrun $params
        ;;
    close)
        djamclose $params
        ;;
    pull)
        djampull $params
        ;;
    comp)
        djamcompile $params
        ;;
    compile)
        djamcompile $params
        ;;
esac
