#!/bin/bash

IDIR="${BASH_SOURCE%/*}"
if [[ ! -d "$IDIR" ]]; then IDIR="$PWD"; fi
source "$IDIR/inc/misc_tools.sh"

show_usage() {
    cat << EOF
Builds a new docker image using the current JAMScript version in the github repo
at https://github.com/citelab/JAMScript.

Usage: djambuild [repo]

djambuild -h
djambuild --help
Prints this help message.

djambuild repository
Builds a new jamscript docker image and uploads to the given repository.

EOF
}


if [ -z $JAMHOME ]; then
    echo "$JAMHOME not set. $JAMHOME needs to point towards a JAMScript source directory."
    die
fi

if [ -z $1 ]; then
    docker build --no-cache -t jamscript $JAMHOME/scripts/install
    docker tag jamscript mahes25/jamscript
    docker push mahes25/jamscript
elif [ $1 == "-h" ] || [ $1 == "--help" ]; then
    show_usage
    exit
else
    docker build --no-cache -t jamscript $JAMHOME/scripts/install
    docker tag jamscript $1
    docker push $1
fi
