#!/bin/bash

die() {
    printf '%s\n' "$1" >&2
    exit 1
}

show_usage() {
    cat << EOF

Runs JAMScript instances in docker containers.
The docker version of the normal 'jam' commands

djam help   - Prints this help
djam clean  - Cleans up the mess left behind by old runs
              Use this command if errors occur due to incomplete runs
djam close  - Close all tmux terminals opened by the 'term' command
djam kill   - Kill a particular application or all active applications
djam list   - Lists all the JAMScript programs running in the system
djam pull   - Pull the given docker image and make it the default
djam run    - Start a device, fog, or cloud
djam term   - Reattach to a tmux terminal ofa running JAMScript instance
              Use the 'list' command to find out the ID to connect.
              

Type 'djam cmd --help' for more help on the specific command.

EOF
}

if [ -z $1 ] || [ $1 == "help" ]; then
    show_usage
    exit 0
fi

jcmd=$1
shift 1
params=$@


case $jcmd in
    list)
        jamlist $params
        ;;
    term)
        jamterm $params
        ;;
    kill)
        jamkill $params
        ;;
    clean)
        jamclean $params
        ;;
    run)
        djamrun $params
        ;;
    close)
        jamclose $params
        ;;
    pull)
        djampull $params
        ;;
    comp)
        djamcompile $params
        ;;
    compile)
        djamcompile $params
        ;;
esac
