#!/bin/bash

die() {
    printf '%s\n' "$1" >&2
    exit 1
}

show_usage() {
    cat << EOF

Runs a collection of jam machine commands.

jam help - prints this help
jam list - lists all the JAMScript programs running in the system
jam term - show the tmux terminals of the running nodes
jam kill - kill a node
jam clean - clean the setup left behind by old runs
jam run - start a device, fog, or cloud



EOF
}

if [ -z $1 ] || [ $1 == "help" ]; then
    show_usage
    exit 0
fi

jcmd=$1
shift 1
params=$@


case $jcmd in
    list)
        jamlist $params
        ;;
    term)
        jamterm $params
        ;;
    kill)
        jamkill $params
        ;;
    clean)
        jamclean $params
        ;;
    run)
        jamrun $params
        ;;
esac
