#!/bin/bash

# Edit the following locations to provide the
TMUX=`which tmux`
if [ -z $TMUX ]; then
    TMUX=/usr/local/bin/tmux
fi

# No need to edit below this line unless you find a bug!

die() {
    printf '%s\n' "$1" >&2
    exit 1
}


closeterm() {
    local tmuxapp=$1

    $TMUX has-session -t $tmuxapp 2>/dev/null
    local res=$?

    if [ $res == "0" ]; then
        $TMUX detach-client -s $tmuxapp
    fi
}

closeall() {

    if [ "$(ls -A $jamfolder)" ]; then

        cd $jamfolder

        for jruns in */; do
            if [ $jruns != "*/" ]; then
                for jport in `ls $jamfolder/$jruns`; do
                    dir=$jamfolder/$jruns$jport
                    if [ -d $dir ]; then
                        if [ -e $dir/tmuxid ]; then
                            local tmuxid=`cat $dir/tmuxid`
                            closeterm $tmuxid
                        fi
                    fi
                done
            fi
        done
    fi
}


show_usage() {
    cat << EOF

jamclose tmux-id
Closes the given terminal.

jamclose
Closes all open terminal (tmux terminals showing running JAMScript devices).

EOF
}

jamfolder=$HOME"/.jamruns"

if [ -z $1 ]; then
    if [ ! -d $jamfolder ]; then
        echo "No running instances of JAMScript."
        exit 0
    fi
    closeall
    exit
fi

if [ $1 == "-h" ] || [ $1 == "--help" ]; then
    show_usage
    exit
fi

if [ ! -d $jamfolder ]; then
    echo "No running instances of JAMScript."
    exit 0
fi

closeterm $1
