#!/bin/bash

# Edit the following locations to provide the correct location if needed
TMUX=`which tmux`
if [ -z $TMUX ]; then
    TMUX=/usr/local/bin/tmux
fi

# No need to edit below this line unless you find a bug!

die() {
    printf '%s\n' "$1" >&2
    exit 1
}

show_usage() {
    cat << EOF
Usage: jamlist [--app=appl_name]

Lists details about all activated instances of JAMScript programs. Use the --app=X
option to limit the listing to programs that match the given name (i.e., X).

EOF
}

checkprocess() {

    if [ -e $1/processId ]; then
        local pid=`cat $1/processId`
        local present=`ps -p $pid | grep node | wc -l`
        if [ $present == "1" ]; then
            running="ps"
        else
            running="none"
        fi
    elif [ -e $1/dockerId ]; then
        local didp=`cat $1/dockerId`
        echo "------> "$didp
        local present=`docker ps --filter id=$didp | grep $didp | wc -l`
        if [ $present == "1" ]; then
            running="docker"
        else
            running="none"
        fi
    fi
    running="none"
}


# save information in global varibales
# appl=
# prog=
saveapplinfo() {

    prog=`echo $1 | awk '{split($0,a,"_"); print a[1]}'`
    appl=`echo $1 | awk '{split($0,a,"_"); split(a[2],b, "/"); print b[1]}'`
}

printnodeinfo() {
    local port=$1
    local mtype=`cat $2/machType`
    local appid=`cat $3/appid`
    local dstore=`cat $2/dataStore`

    if [ $mtype == "device" ]; then
        local tmuxid=`cat $2/tmuxid`
        local cdevs=0
        for pidf in `ls $2/cdevProcessId.*`; do
            local pid=`cat $pidf`
            local pidok=`ps -p $pid | grep a.out | wc -l`
            if [ $pidok == 1 ]; then
                ((cdevs++))
            fi
        done
        printf "%8s %12s %12s %12s %15s %10s %7s %10s\n" "$appid" "$appl" "$prog" "Local:$port" "$dstore" "$mtype" "$cdevs" "$tmuxid"
    else
        printf "%8s %12s %12s %12s %15s %10s %7s %10s\n" "$appid" "$appl" "$prog" "Local:$port" "$dstore" "$mtype" "--" "--"
    fi
}


printdockerinfo() {
    local port=$1
    local mtype=`cat $2/machType`
    local appid=`cat $3/appid`
    local dstore=`cat $2/dataStore`
    local tmuxid=`cat $2/tmuxid`
    local dockerid=`cat $2/dockerId`

    if [ ! `tmux has-session -t $tmuxid` ]; then
        tmuxid="-"
    fi

    echo $mtype
    echo "______ ___ "
    echo $appid
    echo $tmuxid
    echo $dockerid

    if [ $mtype == "device" ]; then
        local cdevs=`docker exec $dockerid jamquery $appid cdevs`
        printf "%8s %12s %12s %12s %15s %10s %7s %10s\n" "$appid" "$appl" "$prog" "Dkr:$dockerid" "$dstore" "$mtype" "$cdevs" "$tmuxid"
    else
        printf "%8s %12s %12s %12s %15s %10s %7s %10s\n" "$appid" "$appl" "$prog" "Dkr:$dockerid" "$dstore" "$mtype" "--" "--"
    fi
}



printheader() {
    printf "\n%8s %12s %12s %12s %15s %10s %7s %10s\n" "ID" "NAME" "PROGRAM" "HOST" "D-STORE" "TYPE" "C-NODES" "TMUX-ID"
}

app=


while :; do
    case $1 in
        -h|-\?|--help)
            show_usage      # Display a usage synopsis.
            exit
            ;;
        -a|--app)           # Takes an option argument; ensure it has been specified.
            if [ "$2" ]; then
                app=$2
                shift
            else
                die 'ERROR: "--app" requires a non-empty option argument.'
            fi
            ;;
        --app=?*)
            app=${1#*=}     # Delete everything up to "=" and assign the remainder.
            ;;
        --app=)            # Handle the case of an empty
            die 'ERROR: "--app" requires a non-empty option argument.'
            ;;
        --)              # End of all options.
            shift
            break
        ;;
        -?*)
            printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
            ;;
        *)               # Default case: No more options, so break out of the loop.
            break
    esac

    shift
done

jamfolder=$HOME"/__jamruns"
if [ ! -d $jamfolder ]; then
    echo "No running instances of JAMScript."
    exit 0
fi

if [ "$(ls -A $jamfolder)" ]; then

    cd $jamfolder

    printheader
    for jruns in */; do
        if [ $jruns != "*/" ]; then
            if [[ $jruns =~ .*$app.* ]]; then
                saveapplinfo $jruns
                for jexs in `ls $jamfolder/$jruns`; do
                    dir=$jamfolder/$jruns$jexs
                    if [ -d $dir ]; then
                        checkprocess $dir
                        if [ $running == "ps" ]; then
                            printnodeinfo $jexs $dir $jamfolder/$jruns
                        elif [ $running == "docker" ]; then
                            printdockerinfo $jexs $dir $jamfolder/$jruns
                        else
                            echo "None"
                        fi
                    fi
                done
            fi
        fi
    done

else
    echo "No running instances of JAMScript."
    exit 0
fi
