#!/bin/bash

# Edit the following locations to provide the
TMUX=`which tmux`
if [ -z $TMUX ]; then
    TMUX=/usr/local/bin/tmux
fi

# No need to edit below this line unless you find a bug!

die() {
    printf '%s\n' "$1" >&2
    exit 1
}

show_usage() {
    cat << EOF

jamterm tmux-id
Shows the background terminals of with the given tmux-id.

EOF
}

if [ -z $1 ] || [ $1 == "-h" ] || [ $1 == "--help" ]; then
    show_usage
    exit
fi

tmuxapp=$1

if $TMUX has-session -t $tmuxapp; then
    # This is overkill.. we would kill instances belonging to other applications
    $TMUX attach -t $tmuxapp
fi
